services:
  postgres_dev:
    container_name: postgres_dev
    image: postgres:16.0-alpine3.18
    ports:
      - "5432:5432"
    env_file:
      - ../.env.development
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - app_network_dev

volumes:
  postgres_dev_data:

networks:
  app_network_dev:
    driver: bridge